ci:
  pipeline-gen:
  - build-job:
      tags: [win64,kitware]
      after_script::
      - Write-Output "Done"
      before_script::
      - .\bin\spack_pwsh.ps1
      - spack compiler find
      script::
      - cd ${SPACK_CONCRETE_ENV_DIR}
      - spack env activate --without-view .
      - spack config add "config:install_tree:projections:${SPACK_JOB_SPEC_PKG_NAME}:'morepadding/{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}'"
      - md ${SPACK_ARTIFACTS_ROOT}/user_data
      - spack --backtrace ci rebuild > >(tee ${SPACK_ARTIFACTS_ROOT}/user_data/pipeline_out.txt) 2> >(tee ${SPACK_ARTIFACTS_ROOT}/user_data/pipeline_err.txt >&2)
  - signing-job-remove:
      script:: no-signing-on-windows
