ci:
  pipeline-gen:
  - build-job:
      after_script::
      - Write-Output "Done"
      before_script::
      - . .\share\spack\spack-env.ps1
      - spack compiler find
      script::
      - spack env activate --without-view ${SPACK_CONCRETE_ENV_DIR}
      - spack config add "config:install_tree:projections:${SPACK_JOB_SPEC_PKG_NAME}:'morepadding/{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}'"
      - md ${SPACK_ARTIFACTS_ROOT}/user_data
      - spack --backtrace ci rebuild > >(tee ${SPACK_ARTIFACTS_ROOT}/user_data/pipeline_out.txt) 2> >(tee ${SPACK_ARTIFACTS_ROOT}/user_data/pipeline_err.txt >&2)
      image: "mcr.microsoft.com/windows/servercore/iis"
  - signing-job-remove:
      script:: no-signing-on-windows
