ci:
  pipeline-gen:
  - build-job:
      script:
      # Test package relocation on linux using a modified prefix
      # This is not well supported on MacOS (https://github.com/spack/spack/issues/37162)
      - - spack config add "config:install_tree:projections:${SPACK_JOB_SPEC_PKG_NAME}:'morepadding/{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}'"
  - build-job-remove:
      image: no-image
  - build-job:
      variables:
        CI_GPG_KEY_ROOT: /etc/protected-runner
